services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # <--- KEEP THIS! This is the "Important" Job B.

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # Removed code volume to prevent Jenkins path errors.

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # Removed code volume to prevent Jenkins path errors.
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bhashaflow
    depends_on:
      - mongodb

  ai-engine:
    build: ./ai-engine
    ports:
      - "8000:8000"

volumes:
  mongo_data: # <--- KEEP THIS! It saves your database data.